#!/usr/bin/env node
var path = require('path');
var logger = require('nlogger').logger(module);
var testrunner = require('nodeunit').testrunner;
logger.debug("Running unit tests with nodeunit");
testrunner.run([path.join('tests', 'unit')]);
